### ISSUE TITLE
Servo and Spline parameter check

### ISSUE THREAD

**Issue by urrsk** [UniversalRobots/Universal_Robots_Client_Library#181]
### Feature summary

Adding checks to avoid a sudden move of the robot using servoj and spline

We have decided to add some limits to how wild command the robot should accept. Motivated by https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/800

The limit we plane to do:
- Limit velocity to 360°/sec as this is the limit for the fastest UR joint (UR3e's wrists joints). This is still very fast, but we expect it to catch where the commanding calls have calculated something wrong.
- Check that spline starting point does is withing the range of 1 mrad. This is a high value for a tolerance, but on the other hand only 1 mm on a meter distance from the single joint.

### Tasks
*To complete this issue involves*
- [ ] Implement the feature
- [ ] Make documentation
- [ ] Make Unit test
- [ ] Test on real hardware

**Comment by fmauch** [comment]
I think this has been implemented in #184
