### ISSUE TITLE
Support for resetting revolution counter for UR3e

### ISSUE THREAD

**Issue by urrsk** [UniversalRobots/Universal_Robots_Client_Library#200]
### Feature summary

The UR3 and UR3e have no revolution limit on its wrist 3 joint. Therefore, add the functionality, of reset the revolution counter, to make this hardware feature more usable through this library, thus ROS and ROS2 driver.

### Suggested implementation
Make the call to the reset_revolution_counter() urscript like zero_ftsensor().
Though the call should not be made a move function is active.

### Related issues
https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/343

### Tasks
*To complete this issue involves*
- [ ] Implement the feature
- [ ] Make documentation that also mention that this is a feature for UR3 and UR3e. And should not be used when there is external cable and tubes attached to the EndOfArmTooling as the cable will limit the joint angle.
- [ ] Make Unit test
- [ ] Make example
- [ ] Test on real hardware

**Comment by fmauch** [comment]
Related: https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/343
